// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrvae_cSyv721Vmifq4SmSRiVgh9DcpwY',
    appId: '1:524901385264:web:4f8d960c4af69d2bc199f5',
    messagingSenderId: '524901385264',
    projectId: 'park-n-lock',
    authDomain: 'park-n-lock.firebaseapp.com',
    databaseURL: 'https://park-n-lock-default-rtdb.firebaseio.com',
    storageBucket: 'park-n-lock.firebasestorage.app',
    measurementId: 'G-68P1YLP91N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB72mT_-dMAjVOcfKAdiL4Ds7-yxo9B-4E',
    appId: '1:524901385264:android:c5caeafdccb76acfc199f5',
    messagingSenderId: '524901385264',
    projectId: 'park-n-lock',
    databaseURL: 'https://park-n-lock-default-rtdb.firebaseio.com',
    storageBucket: 'park-n-lock.firebasestorage.app',
  );
}
